name: Deploy Frontend Next.js

on:
  push:
    branches:
      - main
      - feature/setup-pipeline
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del código
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Instalar dependencias
        run: npm install

      - name: Construir proyecto (Build)
        run: npm run build
        env:
          NEXT_PUBLIC_API_URL: ${{ secrets.BACKEND_URL }}
          
      - name: Zip artifact for deployment
        run: zip -r release.zip . -x ".git/*" ".github/*"

      - name: Desplegar a Azure Web App
        # Esto permite que se despliegue también desde tu rama de prueba para ver si funciona
        if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/feature/setup-pipeline'
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'kallpa-web'
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}